version: '3.8'

services:
    api:
        build: .
        container_name: accounting-api
        ports:
            - '${PORT}:${PORT}'
        env_file:
            - .env
        volumes:
            - ./:/app
        command: npm run dev
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - my-network

    db:
        image: mysql:8.0
        container_name: my-mysql-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '${MYSQL_DOCKER_PORT}:3306'
            - '${MYSQL_X_DOCKER_PORT}:33060'
        volumes:
            - db_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - my-network

volumes:
    db_data:

networks:
    my-network:
        driver: bridge
