version: '3.8'

services:
  api:
    build: .
    container_name: accounting-api
    ports:
      - '3638:3638'
    env_file: 
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    command: npm run dev
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localtest
      MYSQL_USER: myuser
      MYSQL_DATABASE: blotuscode
      MYSQL_PASSWORD: localtest
    ports:
       - '3307:3306'
       - '33061:33060'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge